#ifdef  TEMPL_BEGIN
 
#ifndef ACTUATOR_TEMPLATE_NAME
#define ACTUATOR_TEMPLATE_NAME actuator
#define actuator_MOTOR_POSTITION_MEASSURY_ENABLED 1
#define actuator_MOTOR_SPEED_FILTER_ENABLED 1
#define actuator_SPEED_OV_CURRENT_MODE_ENABLED 1
#define actuator_SPEED_OV_VOLTAGE_CL_MODE_ENABLED 1
#define actuator_POSITION_MODE_OV_CURRENT_ENABLED 1
#define actuator_POSITION_MODE_OV_VOLTAGE_CL_ENABLED 1
#define actuator_ps_CURRENT_LIMMITER_ENABLED 1
#define actuator_ps_CURRENT_REGULATOR_ENABLED 1
#define ACTUATOR_PS_TEMPLATE_SUB_NAME ps
#endif

#define ACTUATOR_PREFIX(name)  _ACTUATOR_PREFIX(name,ACTUATOR_TEMPLATE_NAME)
#define _ACTUATOR_PREFIX(name,prfx)  __ACTUATOR_PREFIX(name,prfx)
#define __ACTUATOR_PREFIX(name,prfx) prfx##_##name


#define PS_TEMPLATE_NAME ACTUATOR_PREFIX(ACTUATOR_PS_TEMPLATE_SUB_NAME)
#define ACTUATOR_PS_TEMPLATE_NAME ACTUATOR_PREFIX(ACTUATOR_PS_TEMPLATE_SUB_NAME)

#define ACTUATOR_PS_PREFIX(name)  _ACTUATOR_PS_PREFIX(name,ACTUATOR_PREFIX(ACTUATOR_PS_TEMPLATE_SUB_NAME))
#define _ACTUATOR_PS_PREFIX(name,prfx)  __ACTUATOR_PS_PREFIX(name,prfx)
#define __ACTUATOR_PS_PREFIX(name,prfx) prfx##_##name

#define ACTUATOR_MOTOR_POSTITION_MEASSURY_ENABLED ACTUATOR_PREFIX(MOTOR_POSTITION_MEASSURY_ENABLED)
#if ACTUATOR_MOTOR_POSTITION_MEASSURY_ENABLED ==1
#define ACTUATOR_MOTOR_SPEED_FILTER_ENABLED ACTUATOR_PREFIX(MOTOR_SPEED_FILTER_ENABLED)
#define ACTUATOR_SPEED_OV_CURRENT_MODE_ENABLED (( ACTUATOR_PREFIX(SPEED_OV_CURRENT_MODE_ENABLED) == 1) && (ACTUATOR_PS_PREFIX(CURRENT_REGULATOR_ENABLED)==1))
#define ACTUATOR_SPEED_OV_VOLTAGE_CL_MODE_ENABLED ((ACTUATOR_PREFIX(SPEED_OV_VOLTAGE_CL_MODE_ENABLED)==1) && (ACTUATOR_PS_PREFIX(CURRENT_LIMMITER_ENABLED)==1))
#define ACTUATOR_POSITION_OV_CURRENT_MODE_ENABLED ((ACTUATOR_PREFIX(POSITION_OV_CURRENT_MODE_ENABLED)==1) && (ACTUATOR_SPEED_OV_CURRENT_MODE_ENABLED==1))
#define ACTUATOR_POSITION_OV_VOLTAGE_CL_MODE_ENABLED ((ACTUATOR_PREFIX(POSITION_OV_VOLTAGE_CL_MODE_ENABLED)==1) && (ACTUATOR_SPEED_OV_VOLTAGE_CL_MODE_ENABLED==1))
#else
#define ACTUATOR_SPEED_OV_CURRENT_MODE_ENABLED 0
#define ACTUATOR_SPEED_OV_VOLTAGE_CL_MODE_ENABLED 0
#define ACTUATOR_POSITION_OV_CURRENT_MODE_ENABLED 0
#define ACTUATOR_POSITION_OV_VOLTAGE_CL_MODE_ENABLED 0
#endif 

#undef TEMPL_BEGIN

#else
	#ifdef  TEMPL_FINISH
		#undef ACTUATOR_TEMPLATE_NAME
		#undef ACTUATOR_PS_TEMPLATE_SUB_NAME
		#undef ACTUATOR_PS_TEMPLATE_NAME
		#undef ACTUATOR_MOTOR_POSTITION_MEASSURY_ENABLED
		#undef ACTUATOR_MOTOR_SPEED_FILTER_ENABLED
		#undef ACTUATOR_SPEED_OV_CURRENT_MODE_ENABLED
		#undef ACTUATOR_SPEED_OV_VOLTAGE_CL_MODE_ENABLED
		#undef ACTUATOR_POSITION_OV_CURRENT_MODE_ENABLED
		#undef ACTUATOR_POSITION_OV_VOLTAGE_CL_MODE_ENABLED
		#undef PS_TEMPLATE_NAME
		#undef  ACTUATOR_PREFIX
		#undef  _ACTUATOR_PREFIX
		#undef  __ACTUATOR_PREFIX

		#undef ACTUATOR_PS_PREFIX
		#undef _ACTUATOR_PS_PREFIX
		#undef __ACTUATOR_PS_PREFIX
		
		#undef TEMPL_FINISH
		
	#else
		#error  invalid prepare mode
	#endif
#endif

