#ifndef mexo_env_common_hpp
#define mexo_env_common_hpp

#define ENV_TYPE_NONE 0

#define ENV_FREEMASTER_CONNECT_TYPE_NONE ENV_TYPE_NONE
#define ENV_FREEMASTER_CONNECT_TYPE_DIRRECT ENV_TYPE_NONE+1
#define ENV_FREEMASTER_CONNECT_TYPE_ABONENT ENV_TYPE_NONE+2

#define ENV_TERMO_CONNECT_TYPE_NONE ENV_TYPE_NONE
#define ENV_TERMO_CONNECT_TYPE_DIRRECT ENV_TYPE_NONE+1
#define ENV_TERMO_CONNECT_TYPE_ABONENT ENV_TYPE_NONE+2

#define ENV_TERMO_PRINT_TYPE_NONE ENV_TYPE_NONE
#define ENV_TERMO_PRINT_TYPE_STD ENV_TYPE_NONE+1
#define ENV_TERMO_PRINT_TYPE_SPECIFIC ENV_TYPE_NONE+2
#define ENV_TERMO_PRINT_TYPE_KEIL ENV_TYPE_NONE+3

#define ENV_NET_FLOW_TYPE_NONE ENV_TYPE_NONE
#define ENV_NET_FLOW_TYPE_DEFAULT ENV_TYPE_NONE+1
#define ENV_NET_FLOW_TYPE_SPECIFIC ENV_TYPE_NONE+2

#include "mexo.env.tunning.hpp"

#ifndef ENV_NET_FLOW_COMMAND_ENABLED
#define ENV_NET_FLOW_COMMAND_ENABLED ENV_TYPE_NONE
#endif 

#ifndef ENV_SETTINGS_STORE_ENABLE
#define ENV_SETTINGS_STORE_ENABLE ENV_TYPE_NONE
#endif

#ifndef ENV_FREEMASTER_CONNECT_TYPE
#define ENV_FREEMASTER_CONNECT_TYPE ENV_FREEMASTER_CONNECT_TYPE_NONE
#endif

#ifndef ENV_TERMO_CONNECT_TYPE
#define ENV_TERMO_CONNECT_TYPE ENV_TERMO_CONNECT_TYPE_NONE
#endif


#ifndef ENV_TERMO_CONNECT_TYPE
#define ENV_TERMO_CONNECT_TYPE ENV_TYPE_NONE
#endif

#ifndef ENV_TERMO_PRINT_TYPE
#define ENV_TERMO_PRINT_TYPE ENV_TERMO_PRINT_TYPE_NONE
#endif 


# if ((ENV_TERMO_CONNECT_TYPE == ENV_TERMO_CONNECT_TYPE_ABONENT) \
||(ENV_FREEMASTER_CONNECT_TYPE == ENV_FREEMASTER_CONNECT_TYPE_ABONENT))
#define  ENV_PROTO_SWITCH_ENABLED 1
#else
#define  ENV_PROTO_SWITCH_ENABLED 0
#endif

#define ROBO_APP_SYSTEM_ENABLED 1

#ifdef ROBO_APP_FREEMASTER_SERIAL_ENABLED 
#error ROBO_APP_FREEMASTER_SERIAL_ENABLED will be defined automatically in mexo.env.common.hpp
#endif

#ifdef ROBO_APP_TERMINAL_ENABLED 
#error ROBO_APP_TERMINAL_ENABLED will be defined automatically in mexo.env.common.hpp
#endif

#ifdef ROBO_APP_PROTO_SWITCH_ENABLED
#error ROBO_APP_PROTO_SWITCH_ENABLED will be defined automatically in mexo.env.common.hpp
#endif

#ifdef ROBO_APP_NET_FLOW_ENABLED
#error ROBO_APP_NET_FLOW_ENABLED will be defined automatically in mexo.env.common.hpp
#endif

#if ENV_FREEMASTER_CONNECT_TYPE != ENV_FREEMASTER_CONNECT_TYPE_NONE
#define ROBO_APP_FREEMASTER_SERIAL_ENABLED 1
#else
#define ROBO_APP_FREEMASTER_SERIAL_ENABLED 0
#endif

#if ENV_TERMO_CONNECT_TYPE != ENV_TERMO_CONNECT_TYPE_NONE
#define ROBO_APP_TERMINAL_ENABLED 1
#else
#define ROBO_APP_TERMINAL_ENABLED 0
#endif

#ifndef ENV_NET_FLOW_TYPE
#define ENV_NET_FLOW_TYPE ENV_NET_FLOW_TYPE_NONE
#endif

#if ENV_NET_FLOW_TYPE!=ENV_NET_FLOW_TYPE_NONE
#define ROBO_APP_NET_FLOW_ENABLED 1
#else
#define ROBO_APP_NET_FLOW_ENABLED 0
#endif

#define ROBO_APP_PROTO_SWITCH_ENABLED ENV_PROTO_SWITCH_ENABLED

#ifndef ENV_SAMPLE_US
#define ENV_SAMPLE_US 50
#endif 

#define FMSTR_REC_TIMEBASE (32768 + ENV_SAMPLE_US)


#endif
