#ifdef  TEMPL_BEGIN

#ifndef PMSM_TEMPLATE_NAME
#define PMSM_TEMPLATE_NAME pmsm
#endif

#define PMSM_PREFIX(name)  _PMSM_PREFIX(name,PMSM_TEMPLATE_NAME)
#define _PMSM_PREFIX(name,prfx)  __PMSM_PREFIX(name,prfx)
#define __PMSM_PREFIX(name,prfx) prfx##_##name

#define PMSM_PS_CROSS_TEMPLATE_NAME PMSM_PS_CROSS_NAME
#define PMSM_ACTUATOR_TEMPLATE_SUB_NAME PMSM_PREFIX(PMSM_ACTUATOR_SUB_NAME)

#define LAT_PREFIX(name)  _LAT_PREFIX(name,PMSM_PS_LAT_NAME)
#define _LAT_PREFIX(name,prfx)  __LAT_PREFIX(name,prfx)
#define __LAT_PREFIX(name,prfx) prfx##_##name

#define LAT_CURRENT_MEASSURY_ENABLED LAT_PREFIX(CURRENT_MEASSURY_ENABLED)
#if LAT_CURRENT_MEASSURY_ENABLED==1 
#define LAT_CURRENT_REGULATOR_ENABLED LAT_PREFIX(CURRENT_REGULATOR_ENABLED)
#define LAT_CURRENT_DIFF_ENABLED LAT_PREFIX(CURRENT_DIFF_ENABLED)
#define LAT_CURRENT_FILTER_ENABLED LAT_PREFIX(CURRENT_FILTER_ENABLED)
#define LAT_CURRENT_FAST_FILTER_ENABLED LAT_PREFIX(CURRENT_FAST_FILTER_ENABLED)
#define LAT_CURRENT_DIFF_FILTER_ENABLED LAT_PREFIX(CURRENT_DIFF_FILTER_ENABLED)
#endif

#undef TEMPL_BEGIN

#else
	#ifdef  TEMPL_FINISH
		#undef PMSM_TEMPLATE_NAME
		#undef  PMSM_PREFIX
		#undef  _PMSM_PREFIX
		#undef  __PMSM_PREFIX

		#undef  PMSM_PS_CROSS_TEMPLATE_NAME
		#undef  PMSM_ACTUATOR_TEMPLATE_SUB_NAME

		#if LAT_CURRENT_MEASSURY_ENABLED==1 
		#undef  LAT_CURRENT_REGULATOR_ENABLED
		#undef  LAT_CURRENT_DIFF_ENABLED
		#undef  LAT_CURRENT_FILTER_ENABLED
		#undef  LAT_CURRENT_DIFF_FILTER_ENABLED
		#undef LAT_ACTUAL_SIGNALS
		#endif
		#undef  LAT_CURRENT_MEASSURY_ENABLED
		#undef  LAT_PREFIX
		#undef  _LAT_PREFIX
		#undef  __LAT_PREFIX
		#undef TEMPL_FINISH
		
	#else
		#error  invalid prepare mode
	#endif
#endif

