/*
#ifndef PS_TEMPLATE_NAME 
#define PS_TEMPLATE_NAME ps
#define ps_CURRENT_MEASSURY_ENABLED 1
#define ps_CURRENT_DIFF_ENABLED 1
#define ps_VOLTAGE_REGULATOR_ENABLED 1
#define ps_CURRENT_REGULATOR_ENABLED 1
#define ps_CURRENT_FILTER_ENABLED 1
#define ps_CURRENT_DIFF_FILTER_ENABLED 1
#endif
*/

#define POWER_SUPPLY_PREFIX(name)  _POWER_SUPPLY_PREFIX(name,PS_TEMPLATE_NAME)
#define _POWER_SUPPLY_PREFIX(name,prfx)  __POWER_SUPPLY_PREFIX(name,prfx)
#define __POWER_SUPPLY_PREFIX(name,prfx) prfx##_##name

#include "mexo/ps.templ.inc.hpp"

#undef  POWER_SUPPLY_PREFIX
#undef  _POWER_SUPPLY_PREFIX
#undef  __POWER_SUPPLY_PREFIX
#undef PS_TEMPLATE_NAME