{
0
#if POWER_SUPPLY_VOLTAGE_REGULATOR_ENABLED == 1
, {
	{
		{} //ref
	}
	, POWER_SUPPLY_PREFIX(VOLTAGE_RAMP_GAIN)
}
#endif

#if POWER_SUPPLY_CURRENT_FILTER_ENABLED==1
, {
	{}
	, POWER_SUPPLY_PREFIX(CURRENT_FILTER_GAIN)
	,{
		POWER_SUPPLY_PREFIX(CURRENT_FILTER_SHIFT_GAIN)
		, POWER_SUPPLY_PREFIX(CURRENT_FILTER_SHIFT_PRESC)
		, POWER_SUPPLY_PREFIX(CURRENT_FILTER_SHIFT_VALUE)
	}
}
#endif

#if POWER_SUPPLY_CURRENT_FAST_FILTER_ENABLED==1
, {
	{}
	, POWER_SUPPLY_PREFIX(CURRENT_FAST_FILTER_SHIFT_VALUE)
}
#endif
#if POWER_SUPPLY_CURRENT_DIFF_FILTER_ENABLED == 1
, {
	{}
	, POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_GAIN)
	,{
		POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_SHIFT_GAIN)
		, POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_SHIFT_PRESC)
		, POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_SHIFT_VALUE)
	}
}
#endif

#if POWER_SUPPLY_CURRENT_REGULATOR_ENABLED == 1
,
#define REGULATOR_PROP_GAIN POWER_SUPPLY_PREFIX(CURRENT_PROP_GAIN)
#define REGULATOR_MODEL_GAIN POWER_SUPPLY_PREFIX(CURRENT_MODEL_GAIN)
#define REGULATOR_DIFF_GAIN POWER_SUPPLY_PREFIX(CURRENT_DIFF_GAIN)
#define REGULATOR_CONTROL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_CONTROL_SHIFT)
#define REGULATOR_MODEL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_MODEL_SHIFT)

#include "mexo/qa.templ.settings.inc.hpp"
#endif


#if POWER_SUPPLY_CURRENT_LIMMITER_ENABLED == 1
,
#define REGULATOR_PROP_GAIN POWER_SUPPLY_PREFIX(CURRENT_PROP_GAIN)
#define REGULATOR_MODEL_GAIN POWER_SUPPLY_PREFIX(CURRENT_MODEL_GAIN)
#define REGULATOR_DIFF_GAIN POWER_SUPPLY_PREFIX(CURRENT_DIFF_GAIN)
#define REGULATOR_CONTROL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_CONTROL_SHIFT)
#define REGULATOR_MODEL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_MODEL_SHIFT)
#define REGULATOR_RAMP_STEP POWER_SUPPLY_PREFIX(CURRENT_LIMMITER_RAMP_STEP)
#define REGULATOR_SIGNAL_MIN POWER_SUPPLY_PREFIX(CURRENT_MIN_LIM)
#define REGULATOR_SIGNAL_MAX POWER_SUPPLY_PREFIX(CURRENT_MAX_LIM)

#include "mexo/lm.templ.settings.inc.hpp"
#endif
}