{
	{ 777 }

#if POWER_SUPPLY_VOLTAGE_REGULATOR_ENABLED == 1
, {
	{
		{} //ref
	}
	, POWER_SUPPLY_PREFIX(VOLTAGE_RAMP_GAIN)
}
#endif

#if POWER_SUPPLY_CURRENT_FILTER_ENABLED==1
	,
	#define FILTER_GAIN POWER_SUPPLY_PREFIX(CURRENT_FILTER_GAIN)
	#define FILTER_SHIFT_GAIN POWER_SUPPLY_PREFIX(CURRENT_FILTER_SHIFT_GAIN)
	#define FILTER_SHIFT_PRESC POWER_SUPPLY_PREFIX(CURRENT_FILTER_SHIFT_PRESC)
	#define FILTER_SHIFT_VALUE POWER_SUPPLY_PREFIX(CURRENT_FILTER_SHIFT_VALUE)
	#include "mexo/filter.templ.settings.inc.hpp"
#endif

#if POWER_SUPPLY_CURRENT_FAST_FILTER_ENABLED==1
, {
	{}
	, POWER_SUPPLY_PREFIX(CURRENT_FAST_FILTER_SHIFT_VALUE)
}
#endif

#if POWER_SUPPLY_CURRENT_DIFF_FILTER_ENABLED == 1
,
	#define FILTER_GAIN POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_GAIN)
	#define FILTER_SHIFT_GAIN POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_SHIFT_GAIN)
	#define FILTER_SHIFT_PRESC POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_SHIFT_PRESC)
	#define FILTER_SHIFT_VALUE POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_SHIFT_VALUE)
	#include "mexo/filter.templ.settings.inc.hpp"
#endif

#if POWER_SUPPLY_CURRENT_REGULATOR_ENABLED == 1
,
#define REGULATOR_PROP_GAIN POWER_SUPPLY_PREFIX(CURRENT_PROP_GAIN)
#define REGULATOR_MODEL_GAIN POWER_SUPPLY_PREFIX(CURRENT_MODEL_GAIN)
#define REGULATOR_DIFF_GAIN POWER_SUPPLY_PREFIX(CURRENT_DIFF_GAIN)
#define REGULATOR_CONTROL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_CONTROL_SHIFT)
#define REGULATOR_MODEL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_MODEL_SHIFT)

#include "mexo/qa.templ.settings.inc.hpp"
#endif

#if POWER_SUPPLY_CURRENT_LIMMITER_ENABLED == 1
,
#define REGULATOR_PROP_GAIN POWER_SUPPLY_PREFIX(CURRENT_PROP_GAIN)
#define REGULATOR_MODEL_GAIN POWER_SUPPLY_PREFIX(CURRENT_MODEL_GAIN)
#define REGULATOR_DIFF_GAIN POWER_SUPPLY_PREFIX(CURRENT_DIFF_GAIN)
#define REGULATOR_CONTROL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_CONTROL_SHIFT)
#define REGULATOR_MODEL_SHIFT POWER_SUPPLY_PREFIX(CURRENT_MODEL_SHIFT)
#define REGULATOR_RAMP_STEP POWER_SUPPLY_PREFIX(CURRENT_LIMMITER_RAMP_STEP)

#include "mexo/lm.templ.settings.inc.hpp"
#endif

}