#ifdef  TEMPL_BEGIN

#ifndef PS_TEMPLATE_NAME
#define PS_TEMPLATE_NAME ps

#define ps_CURRENT_MEASSURY_ENABLED 1
#define ps_CURRENT_DIFF_ENABLED 1
#define ps_VOLTAGE_REGULATOR_ENABLED 1
#define ps_CURRENT_REGULATOR_ENABLED 1
#define ps_CURRENT_LIMMITER_ENABLED 1
#define ps_CURRENT_FILTER_ENABLED 1
#define ps_CURRENT_DIFF_FILTER_ENABLED 1
#endif

#define POWER_SUPPLY_PREFIX(name)  _POWER_SUPPLY_PREFIX(name,PS_TEMPLATE_NAME)
#define _POWER_SUPPLY_PREFIX(name,prfx)  __POWER_SUPPLY_PREFIX(name,prfx)
#define __POWER_SUPPLY_PREFIX(name,prfx) prfx##_##name

#define POWER_SUPPLY_CURRENT_MEASSURY_ENABLED POWER_SUPPLY_PREFIX(CURRENT_MEASSURY_ENABLED)
#define POWER_SUPPLY_VOLTAGE_REGULATOR_ENABLED POWER_SUPPLY_PREFIX(VOLTAGE_REGULATOR_ENABLED)
#if POWER_SUPPLY_CURRENT_MEASSURY_ENABLED==1 
#define POWER_SUPPLY_CURRENT_REGULATOR_ENABLED POWER_SUPPLY_PREFIX(CURRENT_REGULATOR_ENABLED)
#define POWER_SUPPLY_CURRENT_LIMMITER_ENABLED POWER_SUPPLY_PREFIX(CURRENT_LIMMITER_ENABLED)
#define POWER_SUPPLY_CURRENT_DIFF_ENABLED POWER_SUPPLY_PREFIX(CURRENT_DIFF_ENABLED)
#define POWER_SUPPLY_CURRENT_FILTER_ENABLED POWER_SUPPLY_PREFIX(CURRENT_FILTER_ENABLED)
#define POWER_SUPPLY_CURRENT_FAST_FILTER_ENABLED POWER_SUPPLY_PREFIX(CURRENT_FAST_FILTER_ENABLED)
#define POWER_SUPPLY_CURRENT_DIFF_FILTER_ENABLED POWER_SUPPLY_PREFIX(CURRENT_DIFF_FILTER_ENABLED)
#endif
#undef TEMPL_BEGIN

#else
	#ifdef  TEMPL_FINISH
		#undef  POWER_SUPPLY_VOLTAGE_REGULATOR_ENABLED
		#if POWER_SUPPLY_CURRENT_MEASSURY_ENABLED==1 
			#undef  POWER_SUPPLY_CURRENT_REGULATOR_ENABLED
			#undef  POWER_SUPPLY_CURRENT_DIFF_ENABLED
			#undef  POWER_SUPPLY_CURRENT_FILTER_ENABLED
			#undef  POWER_SUPPLY_CURRENT_DIFF_FILTER_ENABLED
			#undef POWER_SUPPLY_ACTUAL_SIGNALS
		#endif
		#undef  POWER_SUPPLY_CURRENT_MEASSURY_ENABLED
		#undef  POWER_SUPPLY_PREFIX
		#undef  _POWER_SUPPLY_PREFIX
		#undef  __POWER_SUPPLY_PREFIX
		#undef PS_TEMPLATE_NAME
		#undef TEMPL_FINISH
	#else
		#error  invalid prepare mode
	#endif
#endif

