#ifndef burst_service_common_hpp
#define burst_service_common_hpp

#define SERVICE_TYPE_NONE 0

#define SERVICE_FREEMASTER_CONNECT_TYPE_NONE SERVICE_TYPE_NONE
#define SERVICE_FREEMASTER_CONNECT_TYPE_DIRRECT SERVICE_TYPE_NONE+1
#define SERVICE_FREEMASTER_CONNECT_TYPE_ABONENT SERVICE_TYPE_NONE+2


#define SERVICE_TERMO_CONNECT_TYPE_NONE SERVICE_TYPE_NONE
#define SERVICE_TERMO_CONNECT_TYPE_DIRRECT SERVICE_TYPE_NONE+1
#define SERVICE_TERMO_CONNECT_TYPE_ABONENT SERVICE_TYPE_NONE+2

#define SERVICE_TERMO_PRINT_TYPE_NONE SERVICE_TYPE_NONE
#define SERVICE_TERMO_PRINT_TYPE_STD SERVICE_TYPE_NONE+1
#define SERVICE_TERMO_PRINT_TYPE_SPECIFIC SERVICE_TYPE_NONE+2
#define SERVICE_TERMO_PRINT_TYPE_KEIL SERVICE_TYPE_NONE+3

#define SERVICE_NET_FLOW_TYPE_NONE SERVICE_TYPE_NONE
#define SERVICE_NET_FLOW_TYPE_DEFAULT SERVICE_TYPE_NONE+1
#define SERVICE_NET_FLOW_TYPE_SPECIFIC SERVICE_TYPE_NONE+2


#define SERVICE_RS485_TAG_NONE 0
#define SERVICE_RS485_TAG_SERIAL 1
#define SERVICE_RS485_TAG_SERIAL_RELAY 2
#define SERVICE_RS485_TAG_MODBUS_RTU_SLAVE 3
#define SERVICE_RS485_TAG_MODBUS_RTU_MASTER 4

#include "service.tunning.hpp"

#ifndef SERVICE_NET_FLOW_COMMAND_ENABLED
#define SERVICE_NET_FLOW_COMMAND_ENABLED SERVICE_TYPE_NONE
#endif 

#ifndef SERVICE_SETTINGS_STORE_ENABLE
#define SERVICE_SETTINGS_STORE_ENABLE SERVICE_TYPE_NONE
#endif

#ifndef SERVICE_FREEMASTER_CONNECT_TYPE
#define SERVICE_FREEMASTER_CONNECT_TYPE SERVICE_FREEMASTER_CONNECT_TYPE_NONE
#endif

#ifndef SERVICE_TERMO_CONNECT_TYPE
#define SERVICE_TERMO_CONNECT_TYPE SERVICE_TERMO_CONNECT_TYPE_NONE
#endif

#ifndef SERVICE_RELAY_PROTO_ENABLED
#define SERVICE_RELAY_PROTO_ENABLED 0
#endif

#ifndef SERVICE_TERMO_PRINT_TYPE
#define SERVICE_TERMO_PRINT_TYPE SERVICE_TERMO_PRINT_TYPE_NONE
#endif 


# if ((SERVICE_TERMO_CONNECT_TYPE == SERVICE_TERMO_CONNECT_TYPE_ABONENT) \
||(SERVICE_FREEMASTER_CONNECT_TYPE == SERVICE_FREEMASTER_CONNECT_TYPE_ABONENT))
#define  SERVICE_PROTO_SWITCH_ENABLED 1
#else
#define  SERVICE_PROTO_SWITCH_ENABLED 0
#endif

#ifdef ROBO_APP_FREEMASTER_SERIAL_ENABLED 
#error ROBO_APP_FREEMASTER_SERIAL_ENABLED will be defined automatically in mexo.SERVICE.common.hpp
#endif

#ifdef ROBO_APP_TERMINAL_ENABLED 
#error ROBO_APP_TERMINAL_ENABLED will be defined automatically in mexo.SERVICE.common.hpp
#endif

#ifdef ROBO_APP_PROTO_SWITCH_ENABLED
#error ROBO_APP_PROTO_SWITCH_ENABLED will be defined automatically in mexo.SERVICE.common.hpp
#endif

#ifdef ROBO_APP_NET_FLOW_ENABLED
#error ROBO_APP_NET_FLOW_ENABLED will be defined automatically in mexo.SERVICE.common.hpp
#endif

#ifdef ROBO_APP_NET_RELEY_ENABLED
#error ROBO_APP_NET_RELEY_ENABLED will be defined automatically in mexo.SERVICE.common.hpp
#endif

#if SERVICE_FREEMASTER_CONNECT_TYPE != SERVICE_FREEMASTER_CONNECT_TYPE_NONE
#define ROBO_APP_FREEMASTER_SERIAL_ENABLED 1
#else
#define ROBO_APP_FREEMASTER_SERIAL_ENABLED 0
#endif

#if SERVICE_TERMO_CONNECT_TYPE != SERVICE_TERMO_CONNECT_TYPE_NONE
#define ROBO_APP_TERMINAL_ENABLED 1
#else
#define ROBO_APP_TERMINAL_ENABLED 0
#endif

#ifndef SERVICE_NET_FLOW_TYPE
#define SERVICE_NET_FLOW_TYPE SERVICE_NET_FLOW_TYPE_NONE
#endif

#if SERVICE_NET_FLOW_TYPE!=SERVICE_NET_FLOW_TYPE_NONE
#define ROBO_APP_NET_FLOW_ENABLED 1
#else
#define ROBO_APP_NET_FLOW_ENABLED 0
#endif

#define ROBO_APP_PROTO_SWITCH_ENABLED SERVICE_PROTO_SWITCH_ENABLED

#ifndef SERVICE_SAMPLE_US
#define SERVICE_SAMPLE_US 50
#endif 

#define FMSTR_REC_TIMEBASE (32768 + SERVICE_SAMPLE_US)

#define ROBO_APP_NET_RELEY_ENABLED  SERVICE_RELAY_PROTO_ENABLED



#ifndef SERVICE_RS485_A_TAG
#define SERVICE_RS485_A_TAG SERVICE_RS485_TAG_NONE
#endif

#ifndef SERVICE_RS485_B_TAG
#define SERVICE_RS485_B_TAG SERVICE_RS485_TAG_NONE
#endif

#ifndef SERVICE_RS485_C_TAG
#define SERVICE_RS485_C_TAG SERVICE_RS485_TAG_NONE
#endif

#if SERVICE_RS485_A_TAG == SERVICE_RS485_TAG_SERIAL
#define SERVICE_RS485_A RT("RS485_A")
#endif

#if SERVICE_RS485_B_TAG == SERVICE_RS485_TAG_SERIAL
#define SERVICE_RS485_B RT("RS485_B")
#endif

#if SERVICE_RS485_C_TAG == SERVICE_RS485_TAG_SERIAL
#define SERVICE_RS485_C RT("RS485_C")
#endif

#ifndef SERVICE_FREEMASTER_MANUAL_POOL_ENABLED
#define SERVICE_FREEMASTER_MANUAL_POOL_ENABLED 0
#endif

#define SERVICE_CRC16_MODBUS_BY_TABLE_ENABLED  \
	(SERVICE_RS485_A_TAG == SERVICE_RS485_TAG_MODBUS_RTU_SLAVE) \
	|| (SERVICE_RS485_A_TAG == SERVICE_RS485_TAG_MODBUS_RTU_MASTER) \
	|| (SERVICE_RS485_B_TAG == SERVICE_RS485_TAG_MODBUS_RTU_SLAVE) \
	|| (SERVICE_RS485_B_TAG == SERVICE_RS485_TAG_MODBUS_RTU_MASTER) \
	|| (SERVICE_RS485_C_TAG == SERVICE_RS485_TAG_MODBUS_RTU_SLAVE) \
	|| (SERVICE_RS485_C_TAG == SERVICE_RS485_TAG_MODBUS_RTU_MASTER) 


#endif

