#include "mexo-drive-1b.config.hpp"

#define joint_pss_VOLTAGE_MIN_LIM -32767
#define joint_pss_VOLTAGE_MAX_LIM 32767
#define joint_pss_VOLTAGE_RAMP_GAIN 300

#if joint_pss_CURRENT_FILTER_ENABLED ==1
#define joint_pss_CURRENT_FILTER_GAIN 7
#define joint_pss_CURRENT_FILTER_SHIFT_GAIN 3
#define joint_pss_CURRENT_FILTER_SHIFT_PRESC 0
#define joint_pss_CURRENT_FILTER_SHIFT_VALUE 0
#endif

#if joint_pss_CURRENT_FAST_FILTER_ENABLED ==1
#define joint_pss_CURRENT_FAST_FILTER_SHIFT_VALUE 3
#endif

#if joint_pss_CURRENT_REGULATOR_ENABLED == 1 || joint_pss_CURRENT_LIMMITER_ENABLED == 1
#define joint_pss_CURRENT_PROP_GAIN 50
#define joint_pss_CURRENT_MODEL_GAIN 700
#define joint_pss_CURRENT_DIFF_GAIN 0
#define joint_pss_CURRENT_CONTROL_SHIFT 7
#define joint_pss_CURRENT_MODEL_SHIFT 10
#endif

#if joint_pss_CURRENT_LIMMITER_ENABLED == 1
#define joint_pss_CURRENT_LIMMITER_RAMP_STEP 500
#endif

#if joint_MOTOR_SPEED_FILTER_ENABLED==1
#define joint_SPEED_FILTER_GAIN 31
#define joint_SPEED_FILTER_SHIFT_GAIN 5
#define joint_SPEED_FILTER_SHIFT_PRESC 5
#define joint_SPEED_FILTER_SHIFT_VALUE 0
#endif

#if joint_SPEED_OV_CURRENT_MODE_ENABLED == 1
#define joint_SPEED_OV_CURRENT_PROP_GAIN 0
#define joint_SPEED_OV_CURRENT_MODEL_GAIN 0
#define joint_SPEED_OV_CURRENT_CONTROL_SHIFT 0
#define joint_SPEED_OV_CURRENT_MODEL_SHIFT 0
#define joint_SPEED_OV_CURRENT_FORCE_GAIN 0
#define joint_SPEED_OV_CURRENT_FORCE_LIM 0
#define joint_SPEED_OV_CURRENT_REF_GAIN 0
#define joint_SPEED_OV_CURRENT_REF_PRESC_SHIFT 0
#endif

#if joint_SPEED_OV_VOLTAGE_CL_MODE_ENABLED == 1
#define joint_SPEED_OV_VOLTAGE_CL_PROP_GAIN 45
#define joint_SPEED_OV_VOLTAGE_CL_MODEL_GAIN 30
#define joint_SPEED_OV_VOLTAGE_CL_CONTROL_SHIFT 0
#define joint_SPEED_OV_VOLTAGE_CL_MODEL_SHIFT 10
#define joint_SPEED_OV_VOLTAGE_CL_FORCE_GAIN 50
#define joint_SPEED_OV_VOLTAGE_CL_FORCE_LIM 7000
#endif

#if joint_POSITION_OV_CURRENT_MODE_ENABLED == 1
#define joint_POSITIONER_OV_CURRENT_PROP_GAIN 1
#define joint_POSITIONER_OV_CURRENT_DIFF_GAIN 0
#define joint_POSITIONER_OV_CURRENT_CONTROL_SHIFT 0
#define joint_POSITIONER_OV_CURRENT_DIFF_QUADR_GAIN 0
#define joint_POSITIONER_OV_CURRENT_DIFF_QUADR_SHIFT 0
#define joint_POSITIONER_OV_CURRENT_DEAD_ZONE 1
#define joint_POSITIONER_OV_CURRENT_CRAWL_SPEED 1
#endif

#if joint_POSITION_OV_VOLTAGE_CL_MODE_ENABLED == 1
#define joint_POSITIONER_OV_VOLTAGE_CL_PROP_GAIN 1
#define joint_POSITIONER_OV_VOLTAGE_CL_DIFF_GAIN 0
#define joint_POSITIONER_OV_VOLTAGE_CL_CONTROL_SHIFT 3
#define joint_POSITIONER_OV_VOLTAGE_CL_DIFF_QUADR_GAIN 0
#define joint_POSITIONER_OV_VOLTAGE_CL_DIFF_QUADR_SHIFT 0
#define joint_POSITIONER_OV_VOLTAGE_CL_DEAD_ZONE 16
#define joint_POSITIONER_OV_VOLTAGE_CL_CRAWL_SPEED 0
#endif